# Generated by Django 3.0.2 on 2020-03-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imdbId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('yearReleased', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('genre', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('poster', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('director_s', models.CharField(blank=True, default=None, max_length=201, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('actors', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_user_info',
            fields=[
                ('newuserID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=10)),
                ('movie_watching_freq', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended', models.BooleanField(blank=True, default=None, null=True)),
                ('user_preference', models.BooleanField(blank=True, default=None, null=True)),
                ('rating', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('watched', models.BooleanField(blank=True, default=None, null=True)),
                ('alg', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('alg_count', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
                ('newuserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.new_user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.BigIntegerField()),
                ('ratings', models.FloatField(blank=True, default=None, null=True)),
                ('new_ratings', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, default=None, null=True)),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.BooleanField(blank=True, default=None, null=True)),
                ('Adventure', models.BooleanField(blank=True, default=None, null=True)),
                ('Animation', models.BooleanField(blank=True, default=None, null=True)),
                ('Children', models.BooleanField(blank=True, default=None, null=True)),
                ('Comedy', models.BooleanField(blank=True, default=None, null=True)),
                ('Crime', models.BooleanField(blank=True, default=None, null=True)),
                ('Documentary', models.BooleanField(blank=True, default=None, null=True)),
                ('Drama', models.BooleanField(blank=True, default=None, null=True)),
                ('Fantasy', models.BooleanField(blank=True, default=None, null=True)),
                ('Film_Noir', models.BooleanField(blank=True, default=None, null=True)),
                ('Horror', models.BooleanField(blank=True, default=None, null=True)),
                ('Musical', models.BooleanField(blank=True, default=None, null=True)),
                ('Mystery', models.BooleanField(blank=True, default=None, null=True)),
                ('Romance', models.BooleanField(blank=True, default=None, null=True)),
                ('Sci_Fi', models.BooleanField(blank=True, default=None, null=True)),
                ('Thriller', models.BooleanField(blank=True, default=None, null=True)),
                ('War', models.BooleanField(blank=True, default=None, null=True)),
                ('Western', models.BooleanField(blank=True, default=None, null=True)),
                ('no_genres_listed', models.BooleanField(blank=True, default=None, null=True)),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie')),
            ],
        ),
    ]
